// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package model

import (
	"time"

	"github.com/google/uuid"
)

type Currency struct {
	ID        uuid.UUID
	Code      string
	Value     float64
	UpdatedAt time.Time
}

type Log struct {
	ID        uuid.UUID
	Duration  int32
	Code      int32
	Request   string
	CreatedAt time.Time
}
