version: "3.8"
services:
  postgres:
    image: $POSTGRES_IMAGE
    container_name: $POSTGRES_CONTAINER
    restart: on-failure
    ports:
      - "$POSTGRES_PORT:5432"
    expose:
      - "$POSTGRES_PORT"
    volumes:
      - b_postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=${POSTGRES_CONTAINER}
  api:
    image: $B_IMAGE
    container_name: $B_CONTAINER
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${B_PORT}:${B_PORT}"
    volumes:
      - "${B_VOLUME}"
    depends_on:
      - postgres

networks:
  default:
    name: $NETWORK

volumes:
  b_postgres: