apikey: abc123456789
apiurl: http://api.local
period: 5
timeout: 5
port: 8080

database:
  dbhost: localhost
  dbport: 5432
  dbuser: test
  dbname: test
  dbpassword: test
  sslmode: disable
  driver: postgres